# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TestApp(object):
    def setupUi(self, TestApp):
        TestApp.setObjectName("TestApp")
        TestApp.resize(981, 648)
        self.centralwidget = QtWidgets.QWidget(TestApp)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 961, 581))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4.addWidget(self.widget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem)
        self.widget_2 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4.addWidget(self.widget_2)
        TestApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TestApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 26))
        self.menubar.setObjectName("menubar")
        TestApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TestApp)
        self.statusbar.setObjectName("statusbar")
        TestApp.setStatusBar(self.statusbar)

        self.retranslateUi(TestApp)
        QtCore.QMetaObject.connectSlotsByName(TestApp)

    def retranslateUi(self, TestApp):
        _translate = QtCore.QCoreApplication.translate
        TestApp.setWindowTitle(_translate("TestApp", "TestApp"))










"""
from pyqtgraph import PlotWidget, plot
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5 import QtGui
import altair as alt
import numpy as np
import sys
import os

from application.widgets import ExamplePrecipWidget
from processing.data_processor import get_data


class Application(QApplication):
    def __init__(self, args, config):
        super(Application, self).__init__(args)
        self.setQuitOnLastWindowClosed(True)
        self.main_window = MainWindow(config)
        self.exec_()


class MainWindow(QMainWindow):
    
        https://blog.devgenius.io/building-your-own-python-data-visualization-desktop-app-f82dd1f9b2ed
        https://doc.qt.io/qtforpython/tutorials/datavisualize/plot_datapoints.html
    
    def __init__(self, config):
        super().__init__()
        self.icon = self.main_layout = self.precip_widget = None

        self.config = config
        self.init_window(config)
        self.show()

    def init_window(self):
        # Adds the configuration options to the main window
        self.icon = QIcon(self.config['icon'])
        self.setWindowTitle(self.config['title'])
        self.setFixedSize(QSize(self.config['size'][0], self.config['size'][1]))
        self.setWindowIcon(self.icon)
        self.main_layout = QVBoxLayout(self)
        self.add_widgets()
        self.setCentralWidget(self.main_layout)

    def add_widgets(self):
        # Add widgets to the main layout
        self.precip_widget = ExamplePrecipWidget()
        self.main_layout.addWidget(self.precip_widget)




--------------------
from tkinter import ttk
import tkinter as tk

import altair as alt
import numpy as np
import sys
import os

from processing.data_processor import get_data
from application.widgets import ExamplePrecipWidget


class Application:
    def __init__(self, config):
        self.root = tk.Tk()
        self.root.geometry(config["size"])
        self.root.title(config['title'])
        main_window = MainWindow(self.root, config)
        self.root.mainloop()


class MainWindow:
    def __init__(self, root, config):
        self.tabs = ttk.Notebook(root)
        self.init_window(config)

    def init_window(self, config):
        tab1 = ttk.Frame(self.tabs)
        ExamplePrecipWidget(tab1).canvas
        self.tabs.add(tab1, text='Map')
        self.tabs.pack(expand=True, fil="both")
        ttk.Label(tab1, text="Map").grid(column=0, row=0, padx=30, pady=30)


"""
